[package]
name = "tdiag-connect"
version = "0.1.1-pre"
authors = ["Andrea Lattuada <andrea@lattuada.me>"]
edition = "2018"
description = "Helpers to obtain traces suitable for diagnostics from timely / differential."
license = "MIT"

[dependencies]
timely = "^0.9"
